Лабораториски/Lab3/171294_Olgica_Mircheva/Lab3/Models/Friend.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace lab3.Models
{
    public class Friend
    {
        [Required]
        [Range(0,200)]
        public int friendId { get; set; }
        [Required]
        public string name { get; set; }
        [Required]
        public string place { get; set; }
    }
}

Лабораториски/Lab3/171294_Olgica_Mircheva/Lab3/Models/FriendList.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace lab3.Models
{
    public class FriendList
    {
        public List<Friend> friends { get; set; }

        public FriendList()
        {
            friends = new List<Friend>();
        }
    }
}

Лабораториски/Lab3/171294_Olgica_Mircheva/Lab3/Controllers/FriendController.cs
using lab3.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace lab3.Controllers
{
    public class FriendController : Controller
    {
        // GET: Friend
        public static List<Friend> friends = new List<Friend>()
        {
            new Friend () { friendId = 0, name = "f0", place = "p0"},
            new Friend () { friendId = 1, name = "f1", place = "p1"},
            new Friend () { friendId = 2, name = "f2", place = "p2"},
            new Friend () { friendId = 3, name = "f3", place = "p3"}
        };

        
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult FriendTable()
        {
            FriendList model = new FriendList();
            model.friends = friends;
            return View(model);
        }

        public ActionResult DeleteFriend(int id)
        {
            friends.RemoveAt(id);
            return View("FriendTable", friends);
        }
       public ActionResult EditFriend(int id)
        {
            Friend friend = friends.ElementAt(id);
            friend.friendId = id;
            return View(friends.ElementAt(id));
        }

        public ActionResult NewFriend()
        {
            Friend model = new Friend();
            return View(model);
        }

        [HttpPost]
        public ActionResult EditFriend(Friend model)
        {
            if(!ModelState.IsValid)
            {
                return View(model);
            } else
            {
                Friend updated = friends.ElementAt(model.friendId);
                updated.name = model.name;
                updated.place = model.place;
               
                return View("FriendTable", friends);
            }
        }

        [HttpPost]
        public ActionResult NewFriend(Friend model)
        {
            if(!ModelState.IsValid)
            {
                return View(model);
            } else
            {
                friends.Add(model);
                return Redirect("FriendTable");
            }
            
        }


    }
}

Лабораториски/Lab3/171294_Olgica_Mircheva/Lab3/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace lab3.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Лабораториски/Lab3/171294_Olgica_Mircheva/Lab3/Views/Friend/EditFriend.cshtml
@model lab3.Models.Friend

@{
    ViewBag.Title = "EditFriend";
}

<h2>EditFriend</h2>

@using (Html.BeginForm("EditFriend", "Friend"))
{
    @Html.HiddenFor(f=>f.friendId)

    <div class="form-group">
        @Html.LabelFor(f => f.friendId)
        @Html.TextBoxFor(f => f.friendId, new { @class = "form-control" })
    </div>

    <div class="form-group">
        @Html.LabelFor(f => f.name)
        @Html.TextBoxFor(f => f.name, new { @class = "form-control" })
    </div>

    <div class="form-group">
        @Html.LabelFor(f => f.place)
        @Html.TextBoxFor(f => f.place, new { @class = "form-control" })
    </div>

    <button type="submit" class="btn btn-primary">Save</button>
    <button type="reset" class="btn btn-danger"> @Html.ActionLink("Back", "FriendTable")</button>
}

Лабораториски/Lab3/171294_Olgica_Mircheva/Lab3/Views/Friend/FriendTable.cshtml
@model lab3.Models.FriendList

@{
    ViewBag.Title = "Friends";
}

<h2>Friends</h2>

@{ 
    int i = 0;
    <table style="padding: 2px; border:solid">
        <tr style="padding:2px; border:solid">
            <td style="padding: 2px; border: solid">Friend ID</td>
            <td style="padding:2px; border: solid">Friend Name</td>
            <td style="padding: 2px; border:solid">Place</td>
            <td style="padding: 2px; border:solid"></td>
            
            
        </tr>

     @foreach(var friend in Model.friends)
     {
         <tr style="padding: 2px; border: solid">
             <td style="padding: 2px; border:solid">@friend.friendId</td>
             <td style="padding: 2px; border:solid">@friend.name</td>
             <td style="padding: 2px; border:solid">@friend.place</td>
             <td style="padding: 2px; border:solid">
                 <button style="color:black; background-color: blue">@Html.ActionLink("Edit", "EditFriend", new { id = i })</button>
                 <button style="color:black; background-color: red">@Html.ActionLink("Delete", "DeleteFriend", new { id = i })</button>
             </td>
         </tr>
         i++;

     }
        
    </table>


}

Лабораториски/Lab3/171294_Olgica_Mircheva/Lab3/Views/Friend/NewFriend.cshtml
@model lab3.Models.Friend

@{
    ViewBag.Title = "NewFriend";
}

<h2>New Friend</h2>


@using (Html.BeginForm("NewFriend", "Friend"))
{

    <div class="form-group">
        @Html.LabelFor(f => f.friendId)
        @Html.TextBoxFor(f => f.friendId, new { @class = "form-control" })
    </div>

    <div class="form-group">
        @Html.LabelFor(f => f.name)
        @Html.TextBoxFor(f => f.name, new { @class = "form-control" })
    </div>

    <div class="form-group">
        @Html.LabelFor(f => f.place)
        @Html.TextBoxFor(f => f.place, new { @class = "form-control" })
    </div>

    <button type="submit" class="btn btn-primary">Save</button>
    <button type="reset" class="btn btn-danger"> @Html.ActionLink("Back", "FriendTable")</button>
}

Лабораториски/Lab3/171294_Olgica_Mircheva/Lab3/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Лабораториски/Lab3/171294_Olgica_Mircheva/Lab3/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Лабораториски/Lab3/171294_Olgica_Mircheva/Lab3/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>